plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example.microservice'
version = '0.1'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(26)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// LOMBOK
	annotationProcessor 'org.projectlombok:lombok:+'
	compileOnly 'org.projectlombok:lombok:+'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:+'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:+'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:+'

	// DOC
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:+'

	// SPRING
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	implementation files('libs/ExampleSdk-0.1.jar')

	// TEST
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
